### ISSUE TITLE
The application freezes when i click to edit a diagram

### ISSUE THREAD

**Issue by woakes070048** [mxmo-co/bpmn_editor#1] opened 2016-07-30 20:52 UTC

**Comment by MaxMorais** [comment] 2016-08-05 03:24
@woakes070048 I'm unable to reproduce this
Can you tell me which version of `frappe` are you using?

Maybe it's related with an issue in v7 that turned `frappe.require` async.

I don't know how to use the new scheme yet

**Comment by MaxMorais** [comment] 2016-08-31 22:21
@woakes070048 fixed with https://github.com/mxmo-co/bpmn_editor/commit/988dfed130f8d31c20683f50dda7162e043f2879

**Closed by MaxMorais** 2016-08-31 22:21 UTC

**Comment by MaxMorais** [comment] 2016-09-05 01:03
@woakes070048 can you give me a feedback if that worked?

**Comment by woakes070048** [comment] 2016-09-05 01:09
It did not work for me

**Comment by MaxMorais** [comment] 2016-09-05 01:12
I'll try install frappe7 to see what is going wrong

**Comment by woakes070048** [comment] 2016-09-05 01:13
Okay thanks
